# 对话大模型名称（如使用 DashScope/通义千问，可配置为 qwen3-max 等）
chat_model_name: qwen3-max
# 向量模型名称（如 "text-embedding-v4"）
embedding_model_name: text-embedding-v4
# rerank模型
rerank_model_name: qwen3-rerank
# 文生图大模型名称
image_model_name: doubao-seedream-5-0-260128
# 文生图服务端点
image_base_url: https://ark.cn-beijing.volces.com/api/v3
# 图片生成默认参数
image_size: 2K
image_response_format: url
image_watermark: true
